# Generated by Django 4.1.5 on 2023-01-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guides',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='designation',
            new_name='descriptiontion',
        ),
    ]
