# Generated by Django 4.1.5 on 2023-01-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_guides_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='descriptiontion',
            new_name='description',
        ),
    ]
