# Generated by Django 4.1.5 on 2023-01-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_descriptiontion_place_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('jobrole', models.TextField()),
                ('img', models.ImageField(upload_to='teammembers')),
            ],
        ),
    ]
